PeoplesSource/Controllers/MessageScheduleController.cs
using Newtonsoft.Json;
using PeoplesSource.Attribute;
using PeoplesSource.Common;
using PeoplesSource.Domain.Services;
using PeoplesSource.Ebay.Models;
using PeoplesSource.Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Serialization;
using PeoplesSource.Data;
using System.Data.Entity.SqlServer;
using System.Globalization;

namespace PeoplesSource.Controllers
{

    public class MessageScheduleController : Controller
    {

        public class MessageScheduleFields
        {
            public decimal MessageScheduleID { get; set; }

            public decimal id { get; set; }

            public string Seller { get; set; }

            public int Sellerid { get; set; }

            public string Subject { get; set; }

            public string Body { get; set; }

            public DateTime SendAt { get; set; }

            public DateTime CreatedDate { get; set; }

            public DateTime DeletedDate { get; set; }

        }

        [Session]
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return Redirect("~/Account/Login?returnUrl=" + null);
            }
        }


        [Session]
        [HttpGet]
        public ActionResult GetMessageSchedule()
        {
            PeopleSourceEntities db = new PeopleSourceEntities();
            List<MessageScheduleFields> Schedule = new List<MessageScheduleFields>();

            var ScheduleList = db.MessageSchedules.Where(p => p.DeletedDate == null).ToList();
            if (ScheduleList.Count > 0)
            {
                foreach (var Data in ScheduleList)
                {
                    Schedule.Add(new MessageScheduleFields
                    {
                        id = Data.MessageScheduleid,
                        MessageScheduleID = Data.MessageScheduleid,
                        Seller = Data.Seller.SellarName,
                        Sellerid = Data.Sellerid,
                        Subject = Data.Subject,
                        Body = Data.Body,
                        SendAt = Data.Send_At
                    });
                }
            }
            return Json(Schedule, JsonRequestBehavior.AllowGet);
        }

        [Session]
        public ActionResult GetSchedulesList(decimal MessageScheduleID)
        {
            var model = new MessageSchedule();
            PeopleSourceEntities db = new PeopleSourceEntities();
            model = db.MessageSchedules.Find(MessageScheduleID);
            return PartialView("GetSchedulesList", model);
            //return Json( model.templateList, JsonRequestBehavior.AllowGet);
        }


        [Session]
        public ActionResult GetAllSeller()
        {
            PeopleSourceEntities db = new PeopleSourceEntities();
            var SellerList = db.Sellers.Select(m => new { SellerName = m.SellarName, SellerID = m.Sellerid }).ToList();
            return Json(new { success = true, SellerList = SellerList }, JsonRequestBehavior.AllowGet);
        }

        [Session]
        public ActionResult EditEbayMessageSchedule(decimal ScheduleID)
        {
            if (ScheduleID != 0)
            {
                PeopleSourceEntities db = new PeopleSourceEntities();
             //   var SellerList = db.Sellers.Select(m => new { SellerName = m.SellarName, SellerID = m.Sellerid }).ToList();
                var ScheduleData = db.MessageSchedules.Select(k => new { Subject = k.Subject, Send_At = k.Send_At, Body = k.Body, MessageScheduleid = k.MessageScheduleid, Sellerid = k.Sellerid, SellerName = k.Seller.SellarName}).FirstOrDefault(m => m.MessageScheduleid == ScheduleID);
                //return Json(new { success = true, SellerList = SellerList, ScheduleData = ScheduleData }, JsonRequestBehavior.AllowGet);
                return Json(new { success = true, ScheduleData = ScheduleData }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false}, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public ActionResult DeleteExistingEbayMsgSchedule(int ScheduleID)
        {

            PeopleSourceEntities db = new PeopleSourceEntities();
            if (ScheduleID != 0)
            {
                var MessagesScheduleList = db.MessageSchedules.Find(ScheduleID);

                if (MessagesScheduleList != null)
                {
                    MessagesScheduleList.DeletedDate = DateTime.Now;
                    db.SaveChanges();
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);

        }

        [Session]
        [HttpPost]
        public ActionResult SaveSchedule(string SellerLists = null, string Subject = null, string Body = null,string SendAt = null)
        {
            try
            {
                if (!string.IsNullOrEmpty(SellerLists) && !string.IsNullOrEmpty(Subject) && !string.IsNullOrEmpty(Body) && !string.IsNullOrEmpty(SendAt))
                {
                    string[] SellerIDs = SellerLists.Split(',');
                    PeopleSourceEntities db = new PeopleSourceEntities();
                    List<MessageSchedule> MessageShceduleList = new List<MessageSchedule>();
                    var sellers = db.Sellers.ToList();
                    foreach (string Sellerid in SellerIDs)
                    {
                        int Id = Convert.ToInt32(Sellerid);
                        DateTime SendDate = DateTime.ParseExact(SendAt, "dd-MM-yyyy HH:mm", CultureInfo.InvariantCulture);
                        MessageShceduleList.Add(new MessageSchedule()
                        {
                            Sellerid = Id,
                            Subject = Subject.Trim(),
                            Body = Body.Trim(),
                            Send_At =SendDate,
                            CreatedDate = DateTime.Now,
                            Status = "InCompleted"
                        });
                    }
                    db.MessageSchedules.AddRange(MessageShceduleList);
                    db.SaveChanges();
                    foreach(var s in MessageShceduleList){
                        s.Seller = new Seller() { SellarName = sellers.FirstOrDefault(m => m.Sellerid == s.Sellerid).SellarName };
                    }
                    return Json(new { success = true, MessageShcedule = MessageShceduleList }, JsonRequestBehavior.AllowGet);
                }
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {

            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }
        
        [Session]
        [HttpPost]
        public ActionResult SaveEditedSchedule(decimal ScheduleID, string Subject, string Body, string SendAt = null)
        {
            try
            {
                if (!string.IsNullOrEmpty(Subject) && !string.IsNullOrEmpty(Body) && !string.IsNullOrEmpty(SendAt))
                {
                   
                    PeopleSourceEntities db = new PeopleSourceEntities();
                    MessageSchedule MessageShceduleList = db.MessageSchedules.Find(ScheduleID);
                    var sellers = db.Sellers.ToList();
                    MessageShceduleList.Subject = Subject;
                    MessageShceduleList.Body = Body;
                    MessageShceduleList.Send_At = DateTime.ParseExact(SendAt, "dd-MM-yyyy HH:mm tt", CultureInfo.InvariantCulture);
                    MessageShceduleList.DeletedDate = null;
                    db.SaveChanges();
                    MessageShceduleList.Seller = new Seller() { SellarName = sellers.FirstOrDefault(m => m.Sellerid == MessageShceduleList.Sellerid).SellarName };
                    return Json(new { success = true, UpDatedValue = MessageShceduleList }, JsonRequestBehavior.AllowGet);
                }
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {

            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        //public ActionResult SaveEditedSchedule(decimal ScheduleID, string SellerLists, string Subject, string Body, string SendAt)
        //{
        //    try
        //    {
        //        if (!string.IsNullOrEmpty(SellerLists) && !string.IsNullOrEmpty(Subject) && !string.IsNullOrEmpty(Body) && !string.IsNullOrEmpty(SendAt.ToString()))
        //        {
        //            string[] SellerIDs = SellerLists.Split(',');
        //            PeopleSourceEntities db = new PeopleSourceEntities();
        //            //   MessageSchedule MessageShceduleList = new <MessageSchedule()>;
        //            var sellers = db.Sellers.ToList();
        //            List<MessageSchedule> NewValue = new List<MessageSchedule>();
        //            var MessageShceduleList = new MessageSchedule();
        //            foreach (string Sellerid in SellerIDs)
        //            {
        //                int SID = Convert.ToInt32(Sellerid);
        //                MessageShceduleList = db.MessageSchedules.FirstOrDefault(m => m.Sellerid == SID && m.MessageScheduleid == ScheduleID);
        //                if (MessageShceduleList != null)
        //                {
        //                    MessageShceduleList.Subject = Subject;
        //                    MessageShceduleList.Body = Body;
        //                    MessageShceduleList.Send_At = SendAt;
        //                    MessageShceduleList.DeletedDate = null;

        //                }
        //                else

PeoplesSource/Views/MessageSchedule/GetMessageSchedule.cshtml
@{
    ViewBag.Title = "Messages Schedule List";
    Layout = null;
}


<div id="jqGrid_container" class="jqGrid">
    <table id="jQGridGroup"></table>
    <div id="jQGridGroupPager"></div>
</div>

<div id="listComment"></div>
<style>
    input.ui-pg-input {
        width: auto;
    }
   
    .ui-jqgrid-view {
        font-size: 11.5px !important;
    }

    div#gbox_jQGridGroup {
        border: 1px solid #aaaaaa !important;
    }

    .ui-jqgrid tr.jqgrow td {
        word-wrap: break-word;
        white-space: pre-wrap;
        white-space: -moz-pre-wrap;
     }

    .clsquantityunit {
        padding-left: 5px !important;
    }

    .paddingright {
        padding-left: 10px !important;
    }
 
</style>

<script type="text/javascript">


    $("#divLoading").show();
    //var mainGridPrefix = "s_";

        $(window).bind('resize', function () {
            var width = $('#jqGrid_container').width();
            $('#jQGridGroup').setGridWidth(width);
        });


        $("#jQGridGroup").jqGrid({
            url: '@Url.Action("GetMessageSchedule","MessageSchedule")',
            datatype: "json",
            //colNames: ['Sender', 'Receiver', 'MessageType', 'Subject', 'Read', 'Attachment', 'Notes', 'Received', 'Actions'],
            colNames: ['MessageScheduleID', 'Sellerid', 'Seller', 'Subject', 'Body', 'SendAt', 'Actions'],
            hideColumns: ["MessageScheduleID", "Sellerid"],
            colModel: [
                
               {
                   name: 'MessageScheduleID',
                   index: 'MessageScheduleID',
                   hidden: true,
               }, {
                   name: 'Sellerid',
                   index: 'Sellerid',
                   hidden: true,
               }, {
                    name: 'Seller',
                    index: 'Seller',
                    width: 15,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {
                        if (rowObject.Seller != null) {
                            var x = "<div class='paddingright'>" + rowObject.Seller;
                            x = x + "</div>";
                            return x;
                        }
                    },
                    sortable: true,
                    editable: false,
                    searchoptions: { sopt: ['cn', 'eq', 'ne', 'bw'] }
                },{
                    name: 'Subject',
                    index: 'Subject',
                    width: 15,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {
                        if (rowObject.Subject != null) {
                            var x = "<div class='paddingright Subject'>" + rowObject.Subject;
                            x = x + "</div>";
                            return x;
                        }
                    },
                    sortable: true,
                    editable: false,
                    searchoptions: { sopt: ['cn', 'eq', 'ne', 'bw'] }
                },{
                    name: 'Body',
                    index: 'Body',
                    width: 15,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {
                        if (rowObject.Body != null) {
                            var x = "<div  class='paddingright Body'>" + rowObject.Body;
                            x = x + "</div>";
                            return x;
                        }
                    },
                    sortable: true,
                    editable: false,
                    searchoptions: { sopt: ['cn', 'eq', 'ne', 'bw'] }
                },{
                    classes:'paddingright SendAt',
                    name: 'SendAt',
                    index: 'SendAt',
                    width: 10,
                    stype: 'date',
                    formatter: 'date',
                    sorttype: 'date',
                    datefmt: 'm/d/Y',
                    formatoptions: { srcformat: 'm/d/Y h:m', newformat: 'd/m/Y  h:i A' },
                    sortable: true,
                    editable: false,    
                    search: true,
                    searchoptions: { sopt: ['eq', 'ne'] }
                },
            //{
            //        name: 'SendAt',
            //        index: 'SendAt',
            //        width: 9,
            //        stype: 'text',
            //        formatter: function (cellvalue, options, rowObject) {
            //            if (rowObject.Body != null) {
            //                var x = "<div style='text-align:center' class='SendAt'>" + rowObject.SendAt;
            //                x = x + "</div>";
            //                return x;
            //            }
            //        },
            //        sortable: true,
            //        editable: false,
            //        searchoptions: { sopt: ['cn', 'eq', 'ne', 'bw'] }
            //    },
                {
                    name: 'Actions',
                    index: 'Actions',
                    width: 5,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {
                        var x = "<div style='text-align:center;'>" +
                                          "<a style='cursor: pointer;color:#1ab394;' onclick='EditEbayMessageSchedule(" + rowObject.MessageScheduleID + "," + rowObject.id + ");'><i class='fa fa-pencil-square-o fa-lg fa-fw' title='Edit Details'></i></a><a style='cursor: pointer;color:#1ab394;'  onclick='DeleteEbayMessageSchedule(" + rowObject.MessageScheduleID + "," + rowObject.id + ");'><i class='fa fa-trash fa-lg fa-fw' title='Delete Details'></i></a>" +
                                       "</div>";
                            
                                return x;
                    },
                    sortable: false,
                    search: false,
                    editable: false,

                }
            ],
            rowNum: 10,
            rowList: [10, 50, 100, 150,200, 1000000],
            mtype: 'GET',   
            pager: '#jQGridGroupPager',
            loadonce: true,
            scroll: false,
            viewrecords: true,
            async:true,
            height: 500,
            autowidth: true,
            shrinkToFit: true,
            ignorecase: true,
            loadComplete: function () {
                $("#jQGridGroupPager").find("select option[value=1000000]").text('All');
                if ($('#jQGridGroup').getGridParam('records') === 0) {
                    oldGrid = $('#jQGridGroup tbody').html();
                    $('#jQGridGroup tbody').html("<div id='NoRecord' style='padding:6px;background:#D8D8D8'>No records found</div>");
                 
                }

                else
                    oldGrid = "";
                InitUI();
            }

        });        


        $(function () {
            $('#side-menu').find('li').removeClass('active');
            $('#side-menu').find('#MessageSchedule').addClass('active');
        });
</script>