PeoplesSource/Controllers/ItemTagController.cs
using Newtonsoft.Json;
using PeoplesSource.Attribute;
using PeoplesSource.Common;
using PeoplesSource.Domain.Services;
using PeoplesSource.Ebay.Models;
using PeoplesSource.Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Serialization;
using PeoplesSource.Data;
using System.Data.Entity.SqlServer;
using System.Globalization;

namespace PeoplesSource.Controllers
{

    public class ItemTagController : Controller
    {
        [Session]
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return Redirect("~/Account/Login?returnUrl=" + null);
            }
        }
            
        [Session]
        [HttpPost]
        public ActionResult SaveTags(string TagList, int Sellerid,string Message)
        {
            try
            {
                if (!string.IsNullOrEmpty(TagList) && Sellerid != 0)
                {
                    PeopleSourceEntities db = new PeopleSourceEntities();
                    List<ItemTag> Data = new List<ItemTag>();
                    var sellers = db.Sellers.ToList();
                    Data.Add(new ItemTag
                    {
                        Sellerid =  Sellerid,
                        ItemTags =  TagList.ToString(),
                        CreateDate = DateTime.Now,
                        Message = Message.Trim()
                    });
                    db.ItemTags.AddRange(Data);
                    db.SaveChanges();
                    foreach (var s in Data)
                    {
                        s.Seller = new Seller() { SellarName = sellers.FirstOrDefault(m => m.Sellerid == s.Sellerid).SellarName };
                    }
                    return Json(new { success = true, Data = Data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false }, JsonRequestBehavior.AllowGet);
                }
            }
            catch(Exception e)
            {
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        [Session]
        public ActionResult GetItemTagDetails()
        {
            try{
                PeopleSourceEntities db = new PeopleSourceEntities();
                var ItemTagList = (from Data in db.ItemTags
                            where Data.DeleteDate == null
                            select new
                            {
                                id =Data.Itemtagid,
                                SellerName = Data.Seller.SellarName,
                                ItemTagID = Data.Itemtagid,
                                ItemTagsList = Data.ItemTags,
                                Sellerid= Data.Sellerid,
                                Message = Data.Message
                            }).ToList();
                return Json(ItemTagList, JsonRequestBehavior.AllowGet);
            } catch(Exception e)
            {
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }
           
        [HttpPost]
        public ActionResult DeleteThankyouMessage(int ItemTagID)
        {

            PeopleSourceEntities db = new PeopleSourceEntities();
            if (ItemTagID != 0)
            {
                var ItemTag = db.ItemTags.Find(ItemTagID);
                if (ItemTag != null)
                {
                    ItemTag.DeleteDate = DateTime.Now;
                    db.SaveChanges();
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);

        }

        [Session]
        public ActionResult EditThankYouMessage(decimal ItemTagID)
        {
            if (ItemTagID != 0)
            {
                PeopleSourceEntities db = new PeopleSourceEntities();
                var ItemtagData = db.ItemTags.Select(k => new { Itemtagid = k.Itemtagid, ItemTags = k.ItemTags, Sellerid = k.Sellerid, Message  = k.Message}).FirstOrDefault(m => m.Itemtagid == ItemTagID);
                return Json(new { success = true, ItemtagData = ItemtagData }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false}, JsonRequestBehavior.AllowGet);
        }
        
        [Session]
        [HttpPost]
        public ActionResult SaveEditedTags(string TagList, int Sellerid, int ItemTagID, string Message)
        {
            try
            {
                if (!string.IsNullOrEmpty(TagList) && Sellerid != 0 && ItemTagID !=0)
                {
                    PeopleSourceEntities db = new PeopleSourceEntities();
                    ItemTag Data = db.ItemTags.Find(ItemTagID);
                    Data.ItemTags = TagList.Trim();
                    Data.Sellerid = Sellerid;
                    Data.Message = Message.Trim();
                    db.SaveChanges();
                    var sellers = db.Sellers.ToList();
                    Data.Seller = new Seller() { SellarName = sellers.FirstOrDefault(m => m.Sellerid == Data.Sellerid).SellarName };
                    return Json(new { success = true, Data = Data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false }, JsonRequestBehavior.AllowGet);
                }
            }
            catch(Exception e)
            {
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

    }
}

PeoplesSource/Views/ItemTag/GetItemTagDetails.cshtml
@{
    ViewBag.Title = "Thank You Messages";
    Layout = null;
}


<div id="jqGrid_container" class="jqGrid">
    <table id="jQGridGroup"></table>
    <div id="jQGridGroupPager"></div>
</div>

<div id="listComment"></div>

<style>
    .paddingright {
        padding-left: 10px !important;
    } 
</style>

<script type="text/javascript">


    $("#divLoading").show();
    //var mainGridPrefix = "s_";

        $(window).bind('resize', function () {
            var width = $('#jqGrid_container').width();
            $('#jQGridGroup').setGridWidth(width);
        });


        $("#jQGridGroup").jqGrid({
            url: '@Url.Action("GetItemTagDetails","ItemTag")',
            datatype: "json",
            colNames: ['ItemTagID', 'ItemTagsList', 'Sellerid', 'SellerName', 'ItemID', 'Message', 'Actions'],
            hideColumns: ["ItemTagID", "ItemTagsList", "Sellerid"],
            colModel: [
                
               {
                   name: 'ItemTagID',
                   index: 'ItemTagID',
                   hidden: true,
               }, {
                   name: 'ItemTagsList',
                   index: 'ItemTagsList',
                   hidden: true,
               }, {
                   name: 'Sellerid',
                   index: 'Sellerid',
                   hidden: true,
               },
                 {
                   name: 'SellerName',
                   index: 'SellerName',
                    width: 10,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {
                        if (rowObject.SellerName != null) {
                            var x = "<div class='paddingright SellerName'>" + rowObject.SellerName;
                            x = x + "</div>";
                            return x;
                        }
                    },
                    sortable: true,
                    editable: false,
                    searchoptions: { sopt: ['cn', 'eq', 'ne', 'bw'] }
                },{
                    name: 'ItemID',
                    index: 'ItemID',
                    width: 15,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {
                        if (rowObject.ItemTagsList != null) {
                            var x = "<div class='paddingright TagList' style='padding:10px;'>";
                            var Taglist = rowObject.ItemTagsList.split(',');
                            $.each(Taglist, function (e, element) {
                                x = x + ('<span style="margin-left:10px;" class="tag label label-info"><i class="fa fa-tag"></i><span style="padding:5px;" class="TagText">' + element + '</span></span>');
                            });
                            x = x + '</div>';
                            return x;
                        }
                    },
                    sortable: true,
                    editable: false,
                    searchoptions: { sopt: ['cn', 'eq', 'ne', 'bw'] }
                },
                 {
                     name: 'Message',
                     index: 'Message',
                     width: 10,
                     stype: 'text',
                     formatter: function (cellvalue, options, rowObject) {
                         if (rowObject.SellerName != null) {
                             var x = "<div class='paddingright Message'>" + rowObject.Message;
                             x = x + "</div>";
                             return x;
                         }
                     },
                     sortable: true,
                     editable: false,
                     searchoptions: { sopt: ['cn', 'eq', 'ne', 'bw'] }
                 },
                {
                    name: 'Actions',
                    index: 'Actions',
                    width: 5,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {
                        var x = "<div style='text-align:center;'>" +
                                          "<a style='cursor: pointer;color:#1ab394;' onclick='EditItemTag(" + rowObject.ItemTagID + "," + rowObject.Sellerid + ");'><i class='fa fa-pencil-square-o fa-lg fa-fw' title='Edit Details'></i></a><a style='cursor: pointer;color:#1ab394;'  onclick='DeleteItemTag(" + rowObject.ItemTagID + ");'><i class='fa fa-trash fa-lg fa-fw' title='Delete Details'></i></a>" +
                                       "</div>";
                            
                                return x;
                    },
                    sortable: false,
                    search: false,
                    editable: false,

                }
            ],
            rowNum: 10,
            rowList: [10, 50, 100, 150,200, 1000000],
            mtype: 'GET',   
            pager: '#jQGridGroupPager',
            scroll: false,
            viewrecords: true,
            async:true,
            height: 500,
            autowidth: true,
            shrinkToFit: true,
            ignorecase: true,
            loadComplete: function () {

                $("#jQGridGroupPager").find("select option[value=1000000]").text('All');
                if ($('#jQGridGroup').getGridParam('records') === 0) {
                    oldGrid = $('#jQGridGroup tbody').html();
                    $('#jQGridGroup tbody').html("<div id='NoRecord' style='padding:6px;background:#D8D8D8'>No records found</div>");
                 
                }

                else
                    oldGrid = "";
                InitUI();
            }

        });        


        $(function () {
            $('#side-menu').find('li').removeClass('active');
            $('#side-menu').find('#MessageSchedule').addClass('active');
        });
</script>