PeoplesSource/Controllers/EbayController.cs
using System;
using System.IO;
using System.Net;
using System.Web.Mvc;
using System.Linq;
using System.Xml;
using System.Xml.Linq;
using PeoplesSource.Attribute;
using PeoplesSource.Common;
using PeoplesSource.Domain.Services;
using PeoplesSource.EWReturn;
using PeoplesSource.Models;
using System.Configuration;
using PeoplesSource.Ebay.Models;
using System.Collections.Generic;
using PeoplesSource.Helpers;


namespace PeoplesSource.Controllers
{
    public class EbayController : Controller
    {
        private readonly ReturnManagementService _c = new ReturnManagementService();
        private readonly ISellerServices _SellerService;
        private readonly ITemplateService _templateService;
        public EbayController
        (
         ISellerServices SellerService,
            ITemplateService templateService
        )
        {
            _SellerService = SellerService.ThrowIfNull("SellerService");
            _templateService = templateService.ThrowIfNull("templateService");
        }
        public string ReturnId;

        #region Return Details
        [Session]
        public ActionResult GetReturnDetails(string retId, int selId)
        {
            PeoplesSource.Data.PeopleSourceEntities db = new Data.PeopleSourceEntities();
            decimal RID = Convert.ToDecimal(retId);
            PeoplesSource.Data.EbayMessage Ebay = db.EbayMessages.FirstOrDefault(m => m.MasterMessageid == RID && m.Type == false && m.Sellerid == selId);
            var sellerdetail = _SellerService.GetSellerDetail(selId);
            ReturnId = Ebay.EbayMessageid.ToString();
            _c.Token = sellerdetail.UserToken;
            _c.IpAddress = sellerdetail.ProxyIP;
            _c.Port = sellerdetail.ProxyPort;
            _c.UserName = sellerdetail.ProxyUserName;
            _c.Password = sellerdetail.ProxyPassword;
            _c.IsCredentialRequired = sellerdetail.IsCredentialsRequired;
            _c.IsProxyRequired = sellerdetail.IsProxyRequired;
            ReturnDetailModel returnDetailItem;
            try
            {
                _c.OperationName = "getReturnDetail";
                var returnDetailReq = GetReturnDetailRequest();
                var returnDetail = _c.getReturnDetail(returnDetailReq); //returns null if returnid is not found
                returnDetailItem = GetReturnDetailItemResponse(returnDetail);
            }
            catch (Exception ex)
            {
                returnDetailItem = null;
                var error = ex.Message;
            }
            Ebay.IsRead = true;
            db.SaveChanges();
            return View(returnDetailItem);
        }
        #endregion
       
       
        #region IssueRefund
        [Session]
        public ActionResult IssueRefund(string retId, int selId)
        {
            EbayIssueRefundModel refundItem = new EbayIssueRefundModel();
            refundItem.SellerId = selId;
            refundItem.ReturnId = retId;

            var sellerdetail = _SellerService.GetSellerDetail(selId);
            ReturnId = retId;
            _c.Token = sellerdetail.UserToken;
            _c.IpAddress = sellerdetail.ProxyIP;
            _c.Port = sellerdetail.ProxyPort;
            _c.UserName = sellerdetail.ProxyUserName;
            _c.Password = sellerdetail.ProxyPassword;
            _c.IsCredentialRequired = sellerdetail.IsCredentialsRequired;
            _c.IsProxyRequired = sellerdetail.IsProxyRequired;
            ReturnDetailModel returnDetailItem;
            try
            {
                _c.OperationName = "getReturnDetail";
                var returnDetailReq = GetReturnDetailRequest();
                var returnDetail = _c.getReturnDetail(returnDetailReq); //returns null if returnid is not found
                returnDetailItem = GetReturnDetailItemResponse(returnDetail);
            }
            catch (Exception ex)
            {
                returnDetailItem = null;
                var error = ex.Message;
            }
            refundItem.RefundDetail = new RefundDetail();
            refundItem.RefundDetail.TotalAmount = returnDetailItem.ActualRefundTotalAmount;

            refundItem.RefundDetail.ItemizedRefund = new List<PeoplesSource.Ebay.Models.ItemizedRefund>();
            if (returnDetailItem.ActualItemizedRefund.Count() > 0)
            {
                foreach (var item in returnDetailItem.ActualItemizedRefund)
                {
                    PeoplesSource.Ebay.Models.ItemizedRefund iR = new PeoplesSource.Ebay.Models.ItemizedRefund();
                    iR.Amount = item.Amount;
                    iR.RefundFeeType = ParseEnum.Parse<PeoplesSource.Ebay.Models.RefundFeeType>(item.FeeType);
                    refundItem.RefundDetail.ItemizedRefund.Add(iR);
                }
            }
            else if (returnDetailItem.EstimateItemizedRefund.Count() > 0)
            {
                foreach (var item in returnDetailItem.EstimateItemizedRefund)
                {
                    PeoplesSource.Ebay.Models.ItemizedRefund iR = new PeoplesSource.Ebay.Models.ItemizedRefund();
                    iR.Amount = item.Amount;
                    iR.RefundFeeType = ParseEnum.Parse<PeoplesSource.Ebay.Models.RefundFeeType>(item.FeeType);
                    refundItem.RefundDetail.ItemizedRefund.Add(iR);
                }
            }
            return View(refundItem);
        }

        [Session]
        [HttpPost]
        public ActionResult IssueRefund(EbayIssueRefundModel IssueRefund)
        {
            var sellerdetail = _SellerService.GetSellerDetail(IssueRefund.SellerId);
            ReturnId = IssueRefund.ReturnId;
            _c.Token = sellerdetail.UserToken;
            _c.IpAddress = sellerdetail.ProxyIP;
            _c.Port = sellerdetail.ProxyPort;
            _c.UserName = sellerdetail.ProxyUserName;
            _c.Password = sellerdetail.ProxyPassword;
            _c.IsCredentialRequired = sellerdetail.IsCredentialsRequired;
            _c.IsProxyRequired = sellerdetail.IsCredentialsRequired;
            RefundModel refundItem = new RefundModel();
            try
            {
                _c.OperationName = "issueRefund";

                var issueRefundrequest = new IssueRefundRequest();
                issueRefundrequest.ReturnId = new ReturnIdType { id = IssueRefund.ReturnId };
                issueRefundrequest.comments = IssueRefund.Comments;
                RefundDetailType rdt = new RefundDetailType();
                rdt.totalAmount = new Amount { Value = IssueRefund.RefundDetail.TotalAmount };
                List<ItemizedRefundDetailType> lstItemizedRefundDetailType = new List<ItemizedRefundDetailType>();
                foreach (var item in IssueRefund.RefundDetail.ItemizedRefund)
                {
                    ItemizedRefundDetailType obj = new ItemizedRefundDetailType();
                    obj.amount = new Amount { Value = item.Amount };
                    obj.refundFeeType = (PeoplesSource.EWReturn.RefundFeeType)item.RefundFeeType;
                    lstItemizedRefundDetailType.Add(obj);
                }
                rdt.itemizedRefund = lstItemizedRefundDetailType.ToArray();
                issueRefundrequest.refundDetail = rdt;

                var issueRefundResponse = _c.issueRefund(issueRefundrequest);
                refundItem = GetIssueRefundResponse(issueRefundResponse);

            }
            catch (Exception ex)
            {
                refundItem = null;
                var error = ex.Message;
            }
            return Json(new { data = refundItem, success = true }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Provide Seller Info
        [Session]
        public ActionResult ProvideSellerInfo(string retId, int selId)
        {
            var sellerdetail = _SellerService.GetSellerDetail(selId);
            ReturnId = retId;
            _c.Token = sellerdetail.UserToken;
            _c.IpAddress = sellerdetail.ProxyIP;
            _c.Port = sellerdetail.ProxyPort;
            _c.UserName = sellerdetail.ProxyUserName;
            _c.Password = sellerdetail.ProxyPassword;
            _c.IsCredentialRequired = sellerdetail.IsCredentialsRequired;
            _c.IsProxyRequired = sellerdetail.IsProxyRequired;
            SellerInfoModel sellerItem;
            try
            {
                _c.OperationName = "provideSellerInfo";
                var iprovideSellerInforequest = GetProvideSellerInfoRequest();
                var provideSellerInfoResponse = _c.provideSellerInfo(iprovideSellerInforequest);
                sellerItem = GetSellerInfoResponse(provideSellerInfoResponse);
            }
            catch (Exception ex)
            {
                sellerItem = null;
                var error = ex.Message;
            }
            return View(sellerItem);

        }

        [Session]
        [HttpPost]
        public ActionResult ProvideSellerInfo(EbayProvideSellerInfoModel EbayProvideSellerInfoModel)
        {
            string retId = "2";
            int selId = 1;
            var sellerdetail = _SellerService.GetSellerDetail(selId);
            ReturnId = retId;
            _c.Token = sellerdetail.UserToken;
            _c.IpAddress = sellerdetail.ProxyIP;
            _c.Port = sellerdetail.ProxyPort;
            _c.UserName = sellerdetail.ProxyUserName;
            _c.Password = sellerdetail.ProxyPassword;
            _c.IsCredentialRequired = sellerdetail.IsCredentialsRequired;
            _c.IsProxyRequired = sellerdetail.IsProxyRequired;
            SellerInfoModel sellerItem;
            try
            {
                _c.OperationName = "provideSellerInfo";
                var iprovideSellerInforequest = GetProvideSellerInfoRequest();
                var provideSellerInfoResponse = _c.provideSellerInfo(iprovideSellerInforequest);
                sellerItem = GetSellerInfoResponse(provideSellerInfoResponse);
            }
            catch (Exception ex)
            {

PeoplesSource/Views/Ebay/IssueRefund.cshtml
@model PeoplesSource.Ebay.Models.IssueRefundModel
@{
    Layout = null;
}
<div class="row">
    <div class="col-lg-12">
        <h3>Issue Refund</h3>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        @if (Model != null)
        {
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("IssueRefund", "Ebay", FormMethod.Post, new { id = "submitIssueRefund" }))
                        {
                            <div class="form-horizontal">
                                @Html.HiddenFor(m => m.SellerId)
                                @Html.HiddenFor(m => m.ReturnId)
                                <div class="row">
                                    <table class="table table-striped table-bordered table-hover footable" data-filter="#filter">
                                        <thead>
                                            <tr>
                                                <th>Fee Type</th>
                                                <th>Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if (Model.RefundDetail.ItemizedRefund.Any())
                                            {
                                                for (int i = 0; i < Model.RefundDetail.ItemizedRefund.Count(); i++)
                                                {
                                                    <tr>
                                                        <td>                                                            
                                                            @Model.RefundDetail.ItemizedRefund[i].RefundFeeType
                                                            @Html.HiddenFor(m => m.RefundDetail.ItemizedRefund[i].RefundFeeType)
                                                        </td>
                                                        <td>
                                                            @Model.RefundDetail.ItemizedRefund[i].Amount
                                                            @Html.HiddenFor(m => m.RefundDetail.ItemizedRefund[i].Amount)
                                                        </td>

                                                    </tr>
                                                }
                                            }
                                            else
                                            {
                                                <tr>
                                                    <td colspan="3">
                                                        <label>No Record Found.</label>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>
                                                    Total
                                                </th>
                                                <th>
                                                    @Model.RefundDetail.TotalAmount
                                                    @Html.HiddenFor(m => m.RefundDetail.TotalAmount)                                                    
                                                </th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>

                                <div class="row">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Comments, htmlAttributes: new { @class = "col-sm-2" })
                                        <div class="col-sm-10">
                                            @Html.TextAreaFor(m => m.Comments, htmlAttributes: new { @class = "form-control input-sm" })
                                            @Html.ValidationMessageFor(m => m.Comments, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        }
        else
        {
            <div>Data Not Available</div>
        }
    </div>
</div>

PeoplesSource/Views/Ebay/ProvideSellerInfo.cshtml
@model PeoplesSource.Models.SellerInfoModel
@{
    Layout = null;
}
<div class="row">
    <div class="col-lg-12">
        <h3>Provide Seller Information</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        @if (Model != null)
        {
            <div class="panel panel-default">
                @*<div class="panel-heading" style="padding: 15px !important">
                    Seller

                </div>*@
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div>
                        <table class="table table-striped table-bordered table-hover footable" data-filter="#filter">                     
                            <tr>
                                <td>Ack</td>
                                <td>@Model.Ack</td>
                            </tr>
                            <tr>
                                <td>Time Stamp</td>
                                <td>@Model.TimeStamp</td>
                            </tr>
                            <tr>
                                <td>Version</td>
                                <td>@Model.Version</td>
                            </tr>
                        </table>
                    </div>
                    <div>
                        <table class="table table-striped table-bordered table-hover footable" data-filter="#filter">
                            <thead>
                                <tr>
                                    <th>Error Id</th>
                                    <th>Error Category</th>
                                    <th>Error Domain</th>                              
                                    <th>Message</th>
                                    <th>Severity</th>
                                    <th>Subdomain</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.SellerErrorItems.Any())
                                {
                                    foreach (var item in Model.SellerErrorItems)
                                    {
                                        <tr>
                                            <td>
                                                @item.ErrorId
                                            </td>
                                            <td>
                                                @item.ErrorCategory
                                            </td>
                                            <td>
                                                @item.ErrorDomain
                                            </td>                                       
                                            <td>
                                                @item.Message
                                            </td>
                                            <td>
                                                @item.Severity
                                            </td>
                                            <td>
                                                @item.Subdomain
                                            </td>
                                        </tr>
                                        <tr style="display: none;">
                                            <td colspan="8">

                                                @if (item.ErrorParameters.Any())
                                                {
                                                    <table class="table table-striped table-bordered table-hover footable" data-filter="#filter">
                                                        <thead>
                                                            <tr>
                                                                <th>Name</th>
                                                                <th>Value</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            @foreach (var itemError in item.ErrorParameters)
                                                            {
                                                                <tr>
                                                                    <td>
                                                                        @itemError.Name
                                                                    </td>
                                                                    <td>
                                                                        @itemError.Value
                                                                    </td>
                                                                </tr>
                                                            }
                                                        </tbody>
                                                    </table>
                                                }
                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="6">
                                            <label>No Record Found.</label>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
        }
        else
        {
            <div>Data Not Available</div>
        }
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

PeoplesSource/Views/Ebay/SendBuyerMessage.cshtml
@{
    Layout = null;
}

@model PeoplesSource.Models.Mail
<html>
<head>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
    <link href="~/Content/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
    <title>SendMessage</title>
    <style>
         .form-group textarea {
            width: 300px;
            height: 85px;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("Send", "Ebay", FormMethod.Post, new { id = "SendMail" }))
    {        
        <div class="row">
            <div class="panel panel-default">
                <div class="col-md-12">
                    @Html.ValidationSummary(true)
                    <div id="templateValidaSummary"></div>
                    <div class="row">
                        <br />
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.HiddenFor(m=>m.ItemId)
                                @Html.HiddenFor(m => m.RecepientId)
                                @Html.HiddenFor(m => m.SellerId)
                                @Html.LabelFor(model => model.MailSubject)
                                @Html.EditorFor(model => model.MailSubject, new { htmlAttributes = new { @class = "form-control", @style = "width:300px" } })
                                @Html.ValidationMessageFor(model => model.MailSubject)
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.LabelFor(model => model.MailBody)
                                @Html.TextAreaFor(model => model.MailBody, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MailBody)
                            </div>
                        </div>
                    </div>
                    @*<div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <input type="button" style="float: left" value="Save" id="saveTemplate" onclick="save();" class="canBtn" />
                                    <input type="button" style="float: left" value="Cancel" class="canBtn" />
                                </div>
                            </div>
                        </div>*@
                </div>
            </div>
        </div>
    }

</body>
</html>

PeoplesSource/Views/Ebay/SendMessage.cshtml
@{
    Layout = null;
}

@model PeoplesSource.Models.Mail
<html>
<head>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
    
    <title>SendMessage</title>

    <script type="text/javascript">
        $(function () {

            $("#TemplateId").change(function () {

                var selectedItem = $(this).val();                
                var txtMailBody = $("#MailBody");

                $.ajax({
                    cache: false,
                    type: "GET",
                    url: '@(Url.Action("GetMessageByTemplate"))',
                    data: { "tempId": selectedItem },
                    success: function (data) {
                        var str = data;                      
                        txtMailBody.val(str);
                    },
                    error: function () {
                        alert('Failed to retrieve data.');
                    }
                });
            });

            $(".modal-dialog").css("width", "35%");
        });

    </script>
    <style>
        .form-group textarea {
            width: 300px;
            height: 85px;
        }
        .custome-md5 {
        width:30%;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("Send", "Ebay", FormMethod.Post, new { id = "SendMail" }))
    {
        <div class="row">
            <div class="col-md-12">
                @Html.ValidationSummary(true)
                    <div id="templateValidaSummary"></div>
                <div class="form-horizontal">
                        <div class="form-group">
                            <div class="col-md-5 control-label custome-md5">
                                @Html.HiddenFor(m => m.ItemId)
                                        @Html.HiddenFor(m => m.RecepientId)
                                        @Html.HiddenFor(m => m.SellerId)
                                        @Html.LabelFor(model => model.MailSubject)
                              </div>
                                <div class="col-md-7">
                                    @Html.EditorFor(model => model.MailSubject, new { htmlAttributes = new { @class = "form-control", @style = "width:300px" } })
                               
                                </div>
                                @Html.ValidationMessageFor(model => model.MailSubject)
                         </div>
                        <div class="form-group">
                            <div class="col-md-5 custome-md5 control-label">
                                @Html.LabelFor(model => model.TemplateId)
                            </div>
                            <div class="col-md-7">@Html.DropDownListFor(model => model.TemplateId, new SelectList(Model.TemplateList, "Id", "Description"), "--Template--", new { @class = "form-control", style = "width:300px" })</div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-5 custome-md5 control-label">
                                @Html.LabelFor(model => model.MailBody)
                            </div>
                            <div class="col-md-7">
                                @Html.TextAreaFor(model => model.MailBody, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            @Html.ValidationMessageFor(model => model.MailBody)
                        </div>
                </div>
            </div>
        </div>
                    @*<div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <input type="button" style="float: left" value="Save" id="saveTemplate" onclick="save();" class="canBtn" />
                                    <input type="button" style="float: left" value="Cancel" class="canBtn" />
                                </div>
                            </div>
                        </div>*@
        
    }

</body>
</html>