PeoplesSource/Models/EbayMessages.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PeoplesSource.Ebay.Models
{
    public class GetMyMessagesResponse
    {
        public DateTime Timestamp { get; set; }

        public string Ack { get; set; }

        public string Version { get; set; }

        public string Build { get; set; }

        public List<Message> Messages { get; set; }
    }

    public class GetOrdersResponse
    {
        public DateTime Timestamp { get; set; }

        public string Ack { get; set; }

        public string Version { get; set; }

        public string Build { get; set; }

        public List<Order> OrderArray { get; set; }
    }

    public class Transaction
    {
        public Item Item { get; set; }
        public Buyer Buyer { get; set; }
    }
    public class Item
    {   
        public decimal ItemID { get; set; }
    }
    public class Buyer
    {
        public string Email { get; set; }
    }
    public class Order
    {
        public List<Transaction> TransactionArray { get; set; }
        public decimal OrderID { get; set; }
        public string OrderStatus { get; set; }
    } 
    public class Message
    {
        
        public string Sender { get; set; }

        public string SendingUserID { get; set; }

        public string RecipientUserID { get; set; }

        public string SendToName { get; set; }

        public string MessageID { get; set; }

        public string ExternalMessageID { get; set; }

        public bool Flagged { get; set; }

        public bool Read { get; set; }

        public DateTime ReceiveDate { get; set; }

        public DateTime ExpirationDate { get; set; }

        public ResponseDetail ResponseDetails { get; set; }

        public string Subject { get; set; }

        public Folder Folder { get; set; }

        public string Text { get; set; }

        public string MessageType { get; set; }

        public bool Replied { get; set; }

        public bool Type { get; set; }

        public DateTime ItemEndTime { get; set; }

        public DateTime? DeleteDate { get; set; }

        public string ItemTitle { get; set; }

        public decimal ItemID { get; set; }

        public List<TagList> TagDetail { get; set; }

        public string Note { get; set; }

        public string Disable { get; set; }
    }
        
    public class ResponseDetail
    {   
        public bool ResponseEnabled { get; set; }

        public string ResponseURL { get; set; }
    }

    public class Folder
    {
        public string FolderID { get; set; }
    }

      public class TagList
        {
            public string TagName { get; set; }
            public int Total { get; set; }
            public bool Checked { get; set; }
            public decimal TagsID { get; set; }
            public DateTime? DeleteDate { get; set; }
        }
        
}

PeoplesSource/Controllers/EbayMessagesController.cs
using Newtonsoft.Json;
using PeoplesSource.Attribute;
using PeoplesSource.Common;
using PeoplesSource.Domain.Services;
using PeoplesSource.Ebay.Models;
using PeoplesSource.Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Serialization;
using PeoplesSource.Data;
using System.Data.Entity.SqlServer;


namespace PeoplesSource.Controllers
{
    public class EbayMessagesController : Controller
    {
        private const int PageSize = 10;
        private readonly ISellerServices _SellerService;

        public EbayMessagesController(ISellerServices SellerService)
        {
            _SellerService = SellerService.ThrowIfNull("SellerService");

        }

        [Session]
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return Redirect("~/Account/Login?returnUrl=" + null);
            }
        }

        [Session]
        public ActionResult GetMessages(int sellerId)
        {
            string error = "";
            PeopleSourceEntities db = new PeopleSourceEntities();
            List<Message> Newview = new List<Message>();
            var MessageList = new List<EbayMessage>();
            MessageList = db.EbayMessages.OrderByDescending(m => m.MessageRecieveDate).OrderBy(m => m.IsRead ? 1 : 0).Where(m => m.Sellerid == sellerId && m.Type == true && m.DeleteDate == null).ToList();
            if (MessageList != null)
            {
                foreach (var MessageData in MessageList)
                {
                    Newview.Add(new Message
                    {
                        ExternalMessageID = MessageData.EbayMessageid.ToString(),
                        MessageID = MessageData.Messageid.ToString(),
                        Subject = MessageData.MessageSubject,
                        SendingUserID = MessageData.Sellerid.ToString(),
                        ReceiveDate = MessageData.MessageRecieveDate.Value != null ? MessageData.MessageRecieveDate.Value : DateTime.Now,
                        ExpirationDate = MessageData.MessageExpiryDate.Value != null ? MessageData.MessageExpiryDate.Value : DateTime.Now,
                        ItemID = MessageData.MessageItemid,
                        RecipientUserID = MessageData.Seller.SellarName,
                        Sender = MessageData.Sender,
                        MessageType = MessageData.MessageType,
                        Read = MessageData.IsRead,
                        TagDetail = (from Data in db.MessageTags
                                     where Data.DeleteDate == null && Data.MasterMessageid == MessageData.Messageid
                                     select new TagList
                                     {
                                         TagsID = Data.Tagid,
                                         TagName = Data.Tag.TagName
                                     }).ToList()
                    });
                }
            }
            return Json(Newview, JsonRequestBehavior.AllowGet);
        }

        [Session]
        public ActionResult GetMessagesById(int sellerId, string messageId)
        {
            PeopleSourceEntities db = new PeopleSourceEntities();
            string error = "";
            GetMyMessagesResponse view = null;
            var seller = db.Sellers.Find(sellerId);
                //_SellerService.GetSeller().Where(x => x.Sellerid == sellerId).FirstOrDefault();
            if (!string.IsNullOrEmpty(seller.UserToken))
            {
                string strReq = @"<?xml version=""1.0"" encoding=""utf-8""?>" +
                                "<GetMyMessagesRequest xmlns=\"urn:ebay:apis:eBLBaseComponents\">" +
                                  "<DetailLevel>ReturnMessages</DetailLevel>" +
                                  "<RequesterCredentials>" +
                                    "<eBayAuthToken>" + seller.UserToken + "</eBayAuthToken>" +
                                  "</RequesterCredentials>" +
                                  "<MessageIDs>" +
                                    "<MessageID>" + messageId + "</MessageID>" +//Can Send upto 10 message ids at a time 
                                  "</MessageIDs>" +
                                "</GetMyMessagesRequest> ";

                XmlDocument xmlDoc = APICall.MakeAPIRequest(strReq, "GetMyMessages", "POST", error, seller.IsProxyRequired,
                                    seller.ProxyIP, seller.ProxyPort, seller.ProxyUsername, seller.ProxyPassword);

                if (error == "")
                {
                    //get the root node, for ease of use
                    XmlNode root = xmlDoc["GetMyMessagesResponse"];
                    if (root != null)
                    {
                        if (root["Errors"] != null)
                        {
                            error += root["Errors"]["ErrorCode"].InnerText + " ";
                            error += root["Errors"]["ShortMessage"].InnerText + " ";
                            error += root["Errors"]["LongMessage"].InnerText;
                        }
                        else
                        {
                            if (root["Ack"].InnerText == "Success")
                            {
                                string jsonText = JsonConvert.SerializeXmlNode(root);
                                string xmls = xmlDoc.InnerXml.Replace(" xmlns=\"urn:ebay:apis:eBLBaseComponents\"", "");
                                using (TextReader sr = new StringReader(xmls))
                                {
                                    XmlSerializer serializer = new XmlSerializer(typeof(GetMyMessagesResponse));
                                    view = serializer.Deserialize(sr) as GetMyMessagesResponse;
                                }
                            }
                        }
                    }
                }
            }
            decimal MID = Convert.ToDecimal(messageId);
            EbayMessage Ebay = db.EbayMessages.FirstOrDefault(m => m.EbayMessageid == MID && m.Type == true && m.Sellerid == sellerId);
            Ebay.IsRead = true;
            db.SaveChanges();
            if (view == null)
                return View("GetMessagesById", view);
            return View("GetMessagesById", view.Messages);

            //if (view == null)
            //    return Json(view, JsonRequestBehavior.AllowGet);
            //return Json(view.Messages, JsonRequestBehavior.AllowGet);

        }

        [Session]
        public ActionResult GetEbayMessagesById(int sellerId, string messageId, string Disable)
        {
            PeopleSourceEntities db = new PeopleSourceEntities();
            string error = "";
            GetMyMessagesResponse view = null;
            var seller = db.Sellers.Find(sellerId);
            var NewView = new List<Message>();
            //_SellerService.GetSeller().Where(x => x.Sellerid == sellerId).FirstOrDefault();
            decimal MID = Convert.ToDecimal(messageId);
            List<EbayMessage> Ebay = db.EbayMessages.Where(m => m.MasterMessageid == MID && m.Type == true && m.Sellerid == sellerId).OrderBy(m=>m.MessageRecieveDate).ToList();
            foreach(var Datas in Ebay)
            {
                Datas.IsRead = true;
                        if (!string.IsNullOrEmpty(seller.UserToken))
                        {
                            string strReq = @"<?xml version=""1.0"" encoding=""utf-8""?>" +
                                            "<GetMyMessagesRequest xmlns=\"urn:ebay:apis:eBLBaseComponents\">" +
                                              "<DetailLevel>ReturnMessages</DetailLevel>" +
                                              "<RequesterCredentials>" +
                                                "<eBayAuthToken>" + seller.UserToken + "</eBayAuthToken>" +
                                              "</RequesterCredentials>" +
                                              "<MessageIDs>" +
                                                "<MessageID>" + Datas.EbayMessageid + "</MessageID>" +//Can Send upto 10 message ids at a time 
                                              "</MessageIDs>" +
                                            "</GetMyMessagesRequest> ";

                            XmlDocument xmlDoc = APICall.MakeAPIRequest(strReq, "GetMyMessages", "POST", error, seller.IsProxyRequired,
                                                seller.ProxyIP, seller.ProxyPort, seller.ProxyUsername, seller.ProxyPassword);

                            if (error == "")
                            {
                                //get the root node, for ease of use
                                XmlNode root = xmlDoc["GetMyMessagesResponse"];
                                if (root != null)
                                {
                                    if (root["Errors"] != null)
                                    {
                                        error += root["Errors"]["ErrorCode"].InnerText + " ";
                                        error += root["Errors"]["ShortMessage"].InnerText + " ";
                                        error += root["Errors"]["LongMessage"].InnerText;
                                    }
                                    else
                                    {
                                        if (root["Ack"].InnerText == "Success")
                                        {
                                            string jsonText = JsonConvert.SerializeXmlNode(root);
                                            string xmls = xmlDoc.InnerXml.Replace(" xmlns=\"urn:ebay:apis:eBLBaseComponents\"", "");
                                            using (TextReader sr = new StringReader(xmls))

PeoplesSource/Views/EbayMessages/GetMessages.cshtml
@model PeoplesSource.Ebay.Models.Message
@using Elmah.ContentSyndication
@using PeoplesSource.Helpers
@{
    ViewBag.Title = "Messages List";
    Layout = null;
    // var pageInfo = ViewData.Get<PageInfo>();
}


<div id="jqGrid_container" class="jqGrid">
    <table id="jQGridGroup"></table>
    <div id="jQGridGroupPager"></div>
</div>

<div id="listComment"></div>
<style>
    input.ui-pg-input {
        width: auto;
    }

    .ui-jqgrid-view {
        font-size: 11.5px !important;
    }

    div#gbox_jQGridGroup {
        border: 1px solid #aaaaaa !important;
    }

    .ui-jqgrid tr.jqgrow td {
        word-wrap: break-word;
        white-space: pre-wrap;
        white-space: -moz-pre-wrap;
     }

    .clsquantityunit {
        padding-left: 5px !important;
    }

    .paddingright {
        padding-left: 10px !important;
    }
</style>

<script type="text/javascript">


    $("#divLoading").show();
    //var mainGridPrefix = "s_";
    $(function () {


        $(window).bind('resize', function () {
            var width = $('#jqGrid_container').width();
            $('#jQGridGroup').setGridWidth(width);
        });


        $("#jQGridGroup").jqGrid({
            url: '@Url.Action("GetMessages", "EbayMessages", new { sellerId = Request.QueryString["sellerId"]})',
            datatype: "json",
            colNames: ['Sender', 'Receiver', 'Subject', 'Read', 'Received', 'Actions'],
            colModel: [

                {
                    name: 'Sender',
                    index: 'Sender',
                    width: 15,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {
                        if (rowObject.Sender != null) {
                            var x = "<div style='padding-top:12px; padding-bottom:12px' class='paddingright'>" + rowObject.Sender;
                            x = x + "</div>";
                            return x;
                        }
                    },
                    sortable: true,
                    editable: false,
                    searchoptions: { sopt: ['cn', 'eq', 'ne', 'bw'] }
                },

                {
                    name: 'RecipientUserID',
                    index: 'RecipientUserID',
                    width: 15,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {

                        if (rowObject.RecipientUserID != null && rowObject.RecipientUserID != undefined) {
                            var x = "<div style='padding-top:12px; padding-bottom:12px' class='paddingright'>" + rowObject.RecipientUserID;
                            x = x + "</div>";
                            return x;
                        }
                    },
                    sortable: true,
                    editable: false,
                    searchoptions: { sopt: ['cn', 'eq', 'ne', 'bw'] }
                },
                {
                    name: 'Subject',
                    index: 'Subject',
                    width: 25,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {

                        if (rowObject.Subject != null) {
                            var x = "<div style='padding-top:12px; padding-bottom:12px' class='paddingright'>" + rowObject.Subject;
                            x = x + "</div>";
                            return x;
                        }
                    },
                    sortable: true,
                    editable: false,
                    searchoptions: { sopt: ['cn', 'eq', 'ne', 'bw'] }
                },
                {
                    name: 'Read',
                    index: 'Read',
                    width: 5,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {

                        if (rowObject.Read != null) {
                            var x = "<div style='padding-top:12px; padding-bottom:12px' class='paddingright'>" + rowObject.Read;
                            x = x + "</div>";
                            return x;
                        }
                    },
                    sortable: true,
                    editable: false,
                    searchoptions: { sopt: ['cn', 'eq', 'ne', 'bw'] }
                },
                {
                    classes:'paddingright',
                    name: 'ReceiveDate',
                    index: 'ReceiveDate',
                    width: 9,
                    stype: 'date',
                    formatter: 'date',
                    sorttype: 'date',
                    datefmt: 'm/d/Y',
                    formatoptions: { srcformat: 'm/d/Y', newformat: 'd/m/Y' },                    
                    sortable: true,
                    editable: false,    
                    search: true,
                    searchoptions: { sopt: ['eq', 'ne'] }
                },
                {
                    name: 'MessageID',
                    index: 'MessageID',
                    width: 6,
                    stype: 'text',
                    formatter: function (cellvalue, options, rowObject) {

                        if (rowObject.MessageID != null) {
                            var x = "<div style='padding-left:5px; padding-top:12px; padding-bottom:12px'>" +
                                        "<a style='cursor: pointer;color:#1ab394;' onclick='ShowMessageDetails(" + @Request.QueryString["sellerId"] + "," + rowObject.ExternalMessageID + ");'><i class='fa fa-envelope fa-lg fa-fw' title='Show Message Details'></i></a><a style='cursor: pointer;color:#1ab394; margin-left:5px;' onclick='ShowMessageDetailsNewPages(" + @Request.QueryString["sellerId"] + "," + rowObject.ExternalMessageID + ");'><i class='fa fa-pencil-square-o fa-lg fa-fw' title='View Details'></i></a>" +
                                    "</div>";
                            return x.replace("Id", rowObject.MessageID);
                        }
                    },

                    sortable: false,
                    search: false,
                    editable: false,

                }
            ],
            rowNum: 10,
            mtype: 'GET',
            pager: '#jQGridGroupPager',
            loadonce: true,
            scroll: false,
            viewrecords: true,
            height: 500,
            autowidth: true,
            shrinkToFit: true,
            ignorecase: true,
            sortname: "ReceiveDate",
            sortorder: "desc",
            loadComplete: function () {
                if ($('#jQGridGroup').getGridParam('records') === 0) {
                    oldGrid = $('#jQGridGroup tbody').html();
                    $('#jQGridGroup tbody').html("<div style='padding:6px;background:#D8D8D8'>No records found</div>");
                }
                else
                    oldGrid = "";
                InitUI();
            }

        });        
    });
    function ShowMessageDetails(sellerId, messageId) {

        var dialog  = new   BootstrapDialog({
            title: 'Message Details',
            closeByBackdrop: false,
            closeByKeyboard: false,
            draggable: true,
            message: $('<div id="CustomizeDialog">Please Wait While Loading .............</div>'),
            onshow: function(dialogRef){
                var Page = $('<div></div>').load('@Url.Action("GetMessagesById", "EbayMessages")' + "?sellerId=" + sellerId + "&messageId=" + messageId,function(responseTxt, statusTxt, xhr){
                    if(statusTxt == 'success')
                    {
                        $('#CustomizeDialog').html(Page);
                    }
                })
            },
        });
        dialog.open();

    }
    function ShowMessageDetailsNewPages(sellerId, messageId) {
        window.open('@Url.Action("GetMessagesById", "EbayMessages")' + "?sellerId=" + sellerId + "&messageId=" + messageId,'_blank');
    }
</script>

PeoplesSource/Views/EbayMessages/GetMessagesById.cshtml
@model List<PeoplesSource.Ebay.Models.Message>
@{
    Layout = null;
}
<div class="row">
    <div class="col-lg-12">
        @if (Model == null)
        {
            <div>Message Detail Not Available.</div>
        }
        else
        {
            <div class="panel panel-default">
                <div class="panel-body">
                    <div>
                        <table class="table table-striped table-bordered table-hover footable" data-filter="#filter">
                            <tr>
                                <th>From</th>
                                <td>@Model[0].Sender</td>
                            </tr>
                            <tr>
                                <th>Subject</th>
                                <td>@Model[0].Subject</td>
                            </tr>
                            <tr>
                                <th>Date</th>
                                <td>@Model[0].ReceiveDate</td>
                            </tr>
                            <tr>
                                <th colspan="2">Message Details</th>
                            </tr>
                            <tr>
                                <td colspan="2" align="center">
                                    @Html.Raw(Model[0].Text)
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<script>

    $(".modal-dialog").css("width", "65%");
</script>

PeoplesSource/Views/EbayMessages/Index.cshtml
@{
    ViewBag.Title = "Message List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" style="margin-top: 10px;" id="divseller">
@*<div class="col-lg-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-content">
                            <div class="file-manager">
                                <h5>Show:</h5>
                                <a class="file-control active" href="#">Ale</a>
                                <a class="file-control" href="#">Documents</a>
                                <a class="file-control" href="#">Audio</a>
                                <a class="file-control" href="#">Images</a>
                                <div class="hr-line-dashed"></div>
                                <button class="btn btn-primary btn-block">Upload Files</button>
                                <div class="hr-line-dashed"></div>
                                <h5>Folders</h5>
                                <h5 class="tag-title">Tags</h5>
                                <ul style="padding: 0" class="tag-list">
                                    <li><a href="">Family<i title="Delete Tag" class="fa fa-trash-o  pull-right"></i><i title="Edit Tag" class="fa fa-pencil-square-o pull-right"></i></a></li>
                                    <li><a href="">Work<i title="Delete Tag" class="fa fa-trash-o  pull-right"></i><i title="Edit Tag" class="fa fa-pencil-square-o pull-right"></i></a></li>
                                    <li><a href="">Home<i title="Delete Tag" class="fa fa-trash-o  pull-right"></i><i title="Edit Tag" class="fa fa-pencil-square-o pull-right"></i></a></li>
                                    <li><a href="">Children<i title="Delete Tag" class="fa fa-trash-o  pull-right"></i><i title="Edit Tag" class="fa fa-pencil-square-o pull-right"></i></a></li>
                                    <li><a href="">Holidays<i title="Delete Tag" class="fa fa-trash-o  pull-right"></i><i title="Edit Tag" class="fa fa-pencil-square-o pull-right"></i></a></li>
                                    <li><a href="">Music<i title="Delete Tag" class="fa fa-trash-o  pull-right"></i><i title="Edit Tag" class="fa fa-pencil-square-o pull-right"></i></a></li>
                                    <li><a href="">Photography<i title="Delete Tag" class="fa fa-trash-o  pull-right"></i><i title="Edit Tag" class="fa fa-pencil-square-o pull-right"></i></a></li>
                                    <li><a href="">Film<i title="Delete Tag" class="fa fa-trash-o  pull-right"></i><i title="Edit Tag" class="fa fa-pencil-square-o pull-right"></i></a></li>
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>*@
                    <div class="col-lg-12" style="margin-bottom:25px;">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h5>Message List</h5>
                               
                            </div>
                            <div class="ibox-content" style="margin-bottom: 20px;">
                                <div class="row">
                                   <div id="SellerListContainer">
                                                 @Html.Partial("GetMessages")
                                   </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>